<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  
  <xacro:include filename="$(find my_robot)/parts/prop/property.xacro"/>

  <xacro:macro name="footprint" >
    <link name="base_footprint">
        <xacro:box_inertia m="0" w="0" d="0" h="0"/>
    </link>
  
    <!-- The base footprint of the robot is located underneath the chassis -->
    <joint name="base_joint" type="fixed">
      <parent link="base_link"/>
      <child link="base_footprint"/>
      <origin xyz="0.0 0.0 ${-(wheel_radius+wheel_zoff)}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>
  
</robot>
